import { Footer } from "@/components/Footer";
import { Header } from "@/components/Header";
import { Oswald } from "next/font/google";

const oswald = Oswald({
  subsets: ["latin"],
});

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={oswald.className}>
      <body>
        <Header />
        <main className="!mt-24 max-w-[1400px] px-30 mx-auto">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
