"use client";

import { getUser } from "@/api/user/user";
import { Footer } from "@/components/Footer";
import { Header } from "@/components/Header";
import { Oswald } from "next/font/google";
import { useEffect } from "react";
import { Toaster } from "react-hot-toast";

const oswald = Oswald({
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Next.js",
//   description: "Generated by Next.js",
// };

export default function RootLayout({ children }: { children: React.ReactNode }) {
  const getUserData = async () => {
    const user = await getUser();

    console.log("USEEEEER", user);
  };

  useEffect(() => {
    getUserData();
  }, []);

  return (
    <html lang="en" className={oswald.className}>
      <body>
        <Toaster />
        <Header />
        <main className="!mt-24 max-w-[1400px] px-30 mx-auto">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
