"use client";

import { getUser } from "@/api/user/user";
import { Footer } from "@/components/Footer";
import { Header } from "@/components/Header";
import "@/i18n/i18n";
import useUserStore from "@/store/useUserStore";
import { Oswald } from "next/font/google";
import { useEffect } from "react";
import { usePathname } from "next/navigation";
import { Toaster } from "react-hot-toast";
import { applyTheme, getStoredTheme } from "@/utils/theme";
import { syncI18nLanguageFromStorage } from "@/i18n/i18n";
import usePostsStore from "@/store/usePostsStore";

const oswald = Oswald({
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Next.js",
//   description: "Generated by Next.js",
// };

export default function RootLayout({ children }: { children: React.ReactNode }) {
  const setUser = useUserStore.use.setUser();
  const fetchPosts = usePostsStore.use.fetchPosts();
  const pathname = usePathname();

  const handleLogin = async () => {
    getUserData();
    await fetchPosts();
  };

  const getUserData = async () => {
    try {
      const user = await getUser();
      setUser(user);
    } catch (error) {
      setUser(null);
    }
  };

  useEffect(() => {
    if (typeof window === "undefined") return;

    if (pathname !== "/login" && pathname !== "/sign-up") {
      getUserData();
      fetchPosts();
    }

    if (!localStorage.getItem("lang")) {
      localStorage.setItem("lang", "en");
    }

    syncI18nLanguageFromStorage();
    applyTheme(getStoredTheme());
  }, [pathname]);

  return (
    <html lang="en" className={oswald.className}>
      <body>
        <Toaster />
        <Header />
        <main className="!mt-24 max-w-[1400px] px-30 mx-auto">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
